services:
  ftp_server:
      image: stilliard/pure-ftpd:hardened
      container_name: pure-ftpd
      ports:
        - "21:21"
        - "30000-30009:30000-30009"
      volumes:
        - "/data:/home/bru/"
        - "./passwd:/etc/pure-ftpd/passwd"
      environment:
        PUBLICHOST: "localhost"
        FTP_USER_NAME: bru
        FTP_USER_PASS: mypass
        FTP_USER_HOME: /home/bru
      command: pure-ftpd -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P localhost -s -A -j -Z -H -4 -E -R -p 30000:30009 -c 5 -C 5